config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-accounting:
      branch: main
      repo: https://github.com/ARGOeu/argo-accounting.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-wheat-newt.sh
        container: qc.acc_dorky-mustard-dormouse
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-accounting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-olivine-dragon.sh
        container: qc.doc_droopy-dandelion-insect
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-magenta-goose.sh
        container: qc.doc_droopy-rose-eleuth
      github.com/ARGOeu/argo-accounting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-charcoal-havanese.sh
        container: qc.doc_whiny-tan-beagle
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-accounting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-alizarin-ocelot.sh
        container: qc.lic_sickly-salmon-chihuahua
  QC.Met:
    repos:
      github.com/ARGOeu/argo-accounting cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-goldenrod-bison.sh
        container: qc.met_muggy-pumpkin-guppy
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-accounting checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-ochre-retriever.sh
        container: qc.sty_dorky-celadon-liger
      github.com/ARGOeu/argo-accounting hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-blue-wolfhound.sh
        container: qc.sty_scummy-aqua-birman
      github.com/ARGOeu/argo-accounting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-harlequin-flamingo.sh
        container: qc.sty_cranky-firebrick-kudu
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-accounting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-flax-bird.sh
        container: qc.ver_lanky-linen-gibbon
timeout: 5400
