config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-accounting:
      branch: devel
      repo: https://github.com/ARGOeu/argo-accounting.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-gamboge-rottweiler.sh
        container: qc.acc_fuzzy-chartreuse-giraffe
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-accounting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-pink-albatross.sh
        container: qc.doc_dorky-gold-dodo
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-beige-fly.sh
        container: qc.doc_pokey-goldenrod-retriever
      github.com/ARGOeu/argo-accounting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-beige-rabbit.sh
        container: qc.doc_gummy-corn-termite
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-accounting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-blue-hound.sh
        container: qc.lic_sleazy-razzmatazz-albatross
  QC.Met:
    repos:
      github.com/ARGOeu/argo-accounting cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.surly-buff-bracke.sh
        container: qc.met_skanky-lime-vulture
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-accounting checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-persimmon-sloth.sh
        container: qc.sty_pasty-bistre-ladybird
      github.com/ARGOeu/argo-accounting hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-sepia-tetra.sh
        container: qc.sty_sloppy-beige-kudu
      github.com/ARGOeu/argo-accounting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-violet-dollar.sh
        container: qc.sty_breezy-amaranth-russel
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-accounting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-puce-bombay.sh
        container: qc.ver_woolly-brown-gar
timeout: 5400
